# Generated by Django 3.1.14 on 2022-10-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exif_photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExifPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
